my homeWork with Avatars
Kulachenkov/school pull request #6
Opened 2022-04-17 06:58 UTC by Kulachenkov

2022-04-17 15:57 UTC, rmuhamedgaliev requested changes
Требуются правки

2022-04-17 15:57 UTC, rmuhamedgaliev commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +{
А зачем вообще ты прибегнул созданию этого конфига? Без него должно все работать

2022-04-17 15:57 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/AvatarService.java
> +        try (
Кто вас так учит писать? Н е делайте так никогда. Всегда обрабатывайте терминальные ошибки. Либо превращайте в райнтайм ошибку и через Spring Controller Advice ловите их и пишите нормальные ошибки

2022-04-17 15:57 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/AvatarService.java
> +        Path filePath = Path.of(avatarsDir, student + "." + getExtensions(avatarFile.getOriginalFilename()));
Почему просто student? Посмотри на название файла какое выходит? если поменяешь имя или возраст, оно стане невалидным. используй ID студента, так правильнее будет

2022-04-17 15:57 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/service/FacultyService.java
>      public Collection<Faculty> findFacultyByStudents(long id) {
Тут какая-то дичь творится. Зачем передавать сюда ID, что бы потом искать по имени, сделай тогда 2 отдельных метода. Так не пишут

2022-04-17 15:57 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/controller/AvatarController.java
> +    public ResponseEntity<String> uploadAvatar(@PathVariable Long studentId, @RequestParam MultipartFile avatar) throws IOException {
И что пользователю делать с твоим исключением? Их надо ловить все и через  ControllerAdvice ловить надо - https://www.baeldung.com/exception-handling-for-rest-with-spring#controlleradvice

2022-04-17 15:57 UTC, rmuhamedgaliev commented on src/main/java/ru/hogwarts/school/model/Avatar.java
> +
для чего такой разрыв? почему везде одинаково не использовать по 1 пустой строке

2022-04-18 18:38 UTC, closed without merging

2022-04-27 23:45 UTC, OKrylov reviewed
В целом по работе все сделано практически верно, но стоит учесть замечания, которые я отметил от Рената + один мой коммент

2022-04-27 23:45 UTC, OKrylov commented on src/main/java/ru/hogwarts/school/service/AvatarService.java
> +@Transactional
аннотация необязательна, так какмы не используес @Lob